const feesStructureData = {
  academicYear: "2025-26",
  description:
    "Our fee structure for the academic year 2025-26 is detailed below. We strive to provide quality education at an affordable cost and offer various payment options.",
  downloadLink: "fee stucture final.jpeg",
  freshAdmission: {
    title: "FEE DETAILS FOR FRESH ADMISSION IN FY 2025-26",
    headers: [
      "Category",
      "Admission on Fee",
      "Caution Money (Refundable)",
      "Development Fee",
      "Insurance Fee",
      "School Diary & Health Card Fee",
      "Activity Fee",
      "Total (One Time + Annual)",
      "E-Learning Fee",
      "Practical Learning Fee",
      "Tuition Fee",
      "Monthly Total",
      "Total (One Time/Annual Charges + 3 Months Charges)",
    ],
    rows: [
      {
        category: "Non AF",
        admissionFee: "₹1804/-",
        cautionMoney: "₹1804/-",
        developmentFee: "₹2074/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalOneTimeAnnual: "₹6902/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1984/-",
        monthlyTotal: "₹2234/-",
        totalWithThreeMonths: "₹13,604/-",
      },
      {
        category: "Offrs",
        admissionFee: "₹1760/-",
        cautionMoney: "₹1760/-",
        developmentFee: "₹2024/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalOneTimeAnnual: "₹6764/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1936/-",
        monthlyTotal: "₹2186/-",
        totalWithThreeMonths: "₹13,322/-",
      },
      {
        category: "Airmen",
        admissionFee: "₹1550/-",
        cautionMoney: "₹1550/-",
        developmentFee: "₹1782/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalOneTimeAnnual: "₹6102/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1705/-",
        monthlyTotal: "₹1955/-",
        totalWithThreeMonths: "₹11,967/-",
      },
      {
        category: "NC (E) / Defence Civilian",
        admissionFee: "₹1380/-",
        cautionMoney: "₹1380/-",
        developmentFee: "₹1587/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalOneTimeAnnual: "₹5567/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1518/-",
        monthlyTotal: "₹1768/-",
        totalWithThreeMonths: "₹10,871/-",
      },
    ],
  },
  existingStudents: {
    title: "FEE DETAILS FOR EXISTING (LKG TO UKG) STUDENTS IN FY 2025-26",
    headers: [
      "Category",
      "Development Fee",
      "Insurance Fee",
      "School Diary & Health Card Fee",
      "Activity Fee",
      "Total Annual Charge",
      "E-Learning Fee",
      "Practical Learning Fee",
      "Tuition Fee",
      "Monthly Total",
      "Total (One Time/Annual Charges + 3 Months Charges)",
    ],
    rows: [
      {
        category: "Non AF Offrs",
        developmentFee: "₹2074/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalAnnualCharge: "₹3294/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1984/-",
        monthlyTotal: "₹2234/-",
        totalWithThreeMonths: "₹9,996/-",
      },
      {
        category: "Offrs",
        developmentFee: "₹2024/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalAnnualCharge: "₹3244/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1936/-",
        monthlyTotal: "₹2186/-",
        totalWithThreeMonths: "₹9,802/-",
      },
      {
        category: "Airmen",
        developmentFee: "₹1782/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalAnnualCharge: "₹3002/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1705/-",
        monthlyTotal: "₹1955/-",
        totalWithThreeMonths: "₹8,867/-",
      },
      {
        category: "NC (E) / Defence Civilian",
        developmentFee: "₹1587/-",
        insuranceFee: "₹70/-",
        diaryHealthCardFee: "₹200/-",
        activityFee: "₹950/-",
        totalAnnualCharge: "₹2807/-",
        eLearningFee: "₹25/-",
        practicalLearningFee: "₹225/-",
        tuitionFee: "₹1518/-",
        monthlyTotal: "₹1768/-",
        totalWithThreeMonths: "₹8,111/-",
      },
    ],
  },
};

